# Используем базовый образ Python
FROM python:alpine

# Устанавливаем зависимости
RUN pip install flask

# Копируем наш серверный код внутрь контейнера
COPY app/server.py .

# Определяем команду запуска сервера при запуске контейнера
CMD ["python", "server.py"]
